name: pharmacy
description: A new Flutter application.

version: 1.1.4+14

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^3.0.2
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.3.1
  barcode_scan2: ^4.2.0
  sqflite: ^2.0.2
  shared_preferences: ^2.0.12
  flutter_svg: ^1.0.3
  http: ^0.13.3
  shimmer: ^2.0.0
  rxdart: ^0.27.1
  yandex_mapkit: ^3.0.3
  permission_handler: ^7.2.0
  geolocator: ^7.1.0
  url_launcher: ^6.0.18
  lottie: ^1.0.1
  package_info: ^2.0.2
  firebase_messaging: ^10.0.8
  firebase_core: ^1.8.0
  flutter_local_notifications: ^9.0.2
  flutter_picker: ^2.0.1
  carousel_slider: ^4.0.0
  device_info_plus: 
  app_settings: ^4.1.0
  flutter_udid: ^2.0.0
  simple_html_css: ^3.0.1
  webview_flutter: ^2.0.8
  appmetrica_plugin: ^0.1.0
  page_transition: ^2.0.2
  web_socket_channel: ^2.1.0
  platform: ^3.1.0
  file: ^6.1.4
  flutter_alice: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/menu/
    - assets/map/
    - assets/anim/
    - assets/icons/
    - assets/img/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
